version: '3'

services:

  test_erlang:
    container_name: test_erlang
    image: asfree/test_erlang:latest

    ports:
      - 5555:8080

    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "3"

